event_management/ajax/urls.py
from django.urls import path,include
from ajax import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('email_validate_for_add_ec/', views.add_ec_email_validate, name='add_ec_email_validate'),
    path('add_ec_data_to_database/', views.add_ec_data_to_database, name='add_ec_data_to_database'),
    path('disable_club/', views.disable_club, name='disable_club'),
    path('enable_club/', views.enable_club, name='enable_club'),
    path('delete_ec/', views.delete_ec, name='delete_ec'),
    path('register_perticipant/',views.register_perticipant,name="register_perticipant"),
    path('check_perticipate_data/',views.check_perticipate_data,name="check_perticipate_data"),
    path('sendemail/',views.sendemail,name="sendemail"),
    path('update_profile/',views.update_profile,name="update_profile"),
    path('change_password/',views.change_password,name="change_password"),
    path('edit_event/',views.edit_event,name="edit_event"),
    path('approve_member_request/',views.approve_member_request,name="approve_member_request"),
    path('remove_member_request/',views.remove_member_request,name="remove_member_request"),

    # path('shownews/',views.shownews,name="shownews"),

]

event_management/club/urls.py
from django.conf.urls import url
 
from club import views
 
app_name = 'club'
 
urlpatterns = [
 
    url(r'^$', views.IndexView.as_view(), name='index'),
 
    url(r'^club/entry/$',views.ClubEntry.as_view(),name='club-entry'),
 
]

event_management/event/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ad/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('user.urls')),
    path('admin/', include('mainadmin.urls')),
    path('club/', include('club.urls')),
    path('ajax/', include('ajax.urls')),
    path('events/', include('eventapp.urls')),
    path('news-notice/', include('newAndNotices.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

event_management/event_management/urls.py
from django.conf.urls import url, include
from django.contrib import admin
 
urlpatterns = [
 
    url(r'^admin/', admin.site.urls),
    url(r'^club/',include('club.urls'))
 
]

event_management/club/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
class Club(models.Model):
    club_name = models.CharField(max_length = 255)
    email = models.EmailField(max_length = 255)
    password = models.CharField(max_length = 255)

    def get_absolute_url(self):
        return reverse("club:index")
    
    

event_management/club/forms.py
from django import forms
from club.models import Clubs,member,Gallery

class registerClub(forms.ModelForm):
    clubname = forms.CharField(max_length = 60, widget = forms.TextInput(attrs={'class':'form-control','placeholder':"Club Name Here"}))
    shortname = forms.CharField(max_length = 60, widget = forms.TextInput(attrs={'class':'form-control','placeholder':"Club Short Name Here"}))
    logo = forms.ImageField(widget = forms.FileInput(attrs={'class':'form-control','placeholder':"Club Logo Here"}))

    class Meta:
        model = Clubs
        fields = ('clubname','shortname','logo')

class update_gallery(forms.ModelForm):
    image = forms.ImageField(label="Gallery Image",widget = forms.FileInput(attrs={'class':'form-control','placeholder':"Gallery Image"}))

    class Meta:
        model = Gallery
        fields = ('image',)

class member_request_form(forms.ModelForm):
    name = forms.CharField(label="Full Name",widget= forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Your Full Name'}))
    email = forms.EmailField(label="Email Address",help_text="We'll never share your email with anyone else.", widget= forms.EmailInput(attrs={'class': 'form-control','aria-describedby':'emailHelp','placeholder':'Enter email'}))
    std_id = forms.CharField(label="Student ID",widget= forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Your Student Id'}))
    phone_number = forms.CharField(label="Phone Number",widget= forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Your Phone Number'}))
    semister = forms.IntegerField(label="Number Of Semister",max_value=21,min_value=0,widget= forms.NumberInput(attrs={'class': 'form-control','placeholder':'Enter your semister'}))
    completed_credit = forms.IntegerField(label="Completed Credit",min_value=0,widget= forms.NumberInput(attrs={'class': 'form-control','placeholder':'Enter your completed credit'}))


    class Meta:
        model = member
        fields = ('name','std_id','email','phone_number','semister','completed_credit')

event_management/club/views.py
from django.views import generic
from django.views.generic.edit import CreateView
from club.models import Club
from django.urls import reverse_lazy

class IndexView(generic.ListView):
    context_object_name = 'club_list'
    template_name = 'club/index.html'
 
    def get_queryset(self):
        return Club.objects.all()
 
# view for the product entry page
class ClubEntry(CreateView):
    model = Club
    fields = ['club_name', 'email', 'password']

event_management/club/templates/club/club_form.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <div class="container register">
        <div class="row">
            <div class="col-md-3 register-left">
                <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt="" />
                <h3>Welcome</h3>
                <p>Register your club now and post events!</p>
                <input type="submit" name="" value="Go to Main Page" /><br />
            </div>
            <div class="col-md-9 register-right">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <h3 class="register-heading">Register Your Club</h3>
                        <form class="row register-form" action="{% url 'club:club-entry' %}" method="post">
                            {% csrf_token %}
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Club Name" name="clubName"
                                        required />
                                </div>
                                <br>
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email"
                                        placeholder="Club Email Address" required />
                                </div>
                                <br>
                                <div class="form-group">
                                    <input type="password" class="form-control" placeholder="Password" name="password"
                                        required />
                                </div>
                                <input type="submit" class="btnRegister" value="Register" />
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
</body>

</html>

event_management/club/templates/club/form-template.html
{% for field in form %}
    <div class="form-group">
        <div >
            <span class="text-danger la">{{ field.errors }}</span>
        </div>
        <label  >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

event_management/club/templates/club/index.html
{% if club_list %}
{% for eachclub in club_list %}
<ul>
    <li>
        <p> Club Name: {{ eachclub.club_name }}</p>
        <p>Email Address: {{ eachclub.email }}</p>
    </li>
</ul>

{% endfor %}

{% else %}
<h1>No entries found on the database.</h1>


{% endif %}
<form action="{% url 'club:club-entry'  %}" method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit" class="btn btn-default btn-sm">Add A New Club</button>
</form>